# Generated by Django 2.1.4 on 2019-01-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_msch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msch',
            options={'verbose_name': 'aa'},
        ),
    ]
