# Generated by Django 2.1.4 on 2019-01-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190118_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msch',
            options={'verbose_name': '1'},
        ),
    ]
