# Generated by Django 2.1.4 on 2019-01-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190118_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msch',
            options={'verbose_name': '개설멘토스쿨'},
        ),
    ]
