# Generated by Django 2.1.4 on 2019-01-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190118_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msch',
            options={'verbose_name': '개설멘토스쿨', 'verbose_name_plural': '개설멘토스쿨'},
        ),
    ]
